####### This is an EXAMPLE config file!!
####### Changes made here will not effect demo site

languageCode = "en-us"
title = "RSA Analysis"
baseURL = "https://prisha247.github.io/QuantumCryptography/"
theme = "hugo-html5up-alpha"
disqusShortname = ""
publishDir = "docs"

[params]
  description = "A Study into RSA"
  images = ["images/homepagebg.jpg"]
  author = "Hugo Port: [Nelson/Roberto](https://nelsonroberto.com/)"
  copyright = "© Untitled. All rights reserved."
  design = "Design: [HTML5 UP](http://html5up.net/)"
  mainSections = ["blog"]

### Footer Social Media Links ###
# [[params.share]]
# title = "facebook"
# icon = "fa-facebook-f" # fontawesome icons https://fontawesome.com/icons?d=gallery&s=brands
# link = "https://www.facebook.com/"

# [[params.share]]
# title = "twitter"
# icon = "fa-twitter"
# link = "https://twitter.com/"

#[[params.share]]
#title = "linkedin"
#icon = "fa-linkedin"
#link = "https://www.linkedin.com"

### For Pages the .RelPermalink must match the menu .URL
### For sections the name/directory must match the menu .Identifier
[menu]

  [[menu.main]]
    identifier = "rsamath"
    name = "RSA Math"
    url = "/rsamath/"
    weight = 20

  [[menu.main]]
    identifier = "quantum"
    name = "Quantum Computing"
    url = "/quantum/"
    weight = 30

  [[menu.main]]
    identifier = "Theorems and Proofs"
    name = "Theorems and Proofs"
    url = "/proofs/"
    weight = 40

  [[menu.main]]
    identifier = "general"
    name = "Cryptography"
    url = "/general/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About Us"
    url = "/about/"
    weight = 50

[markup.goldmark.renderer]
  unsafe= true
